const T={empty:'Import daily prescriptions to view results.',select:"Select a drug in Today's Sharing Tasks first.",batchAll:'All Batches',historyEmpty:'No history records.',saved:'Current plan saved.'};
let drugs=(window.DRUG_KNOWLEDGE_SEED||[]).map((d,i)=>mkDrug(d,i));
let orders=[],plans=[],selectedDrug=null,history=JSON.parse(localStorage.getItem('dosepilot_history_en')||'[]'),expanded=null;
function n(v){return Number(String(v||'').match(/\d+(\.\d+)?/)?.[0]||0)}
function r(v){return Number(v||0).toFixed(2).replace(/\.00$/,'').replace(/0$/,'')}
function money(v){return '¥'+Math.round(v||0).toLocaleString('en-US')}
function norm(v){return String(v||'').replace(/[（(].*?[）)]/g,'').replace(/\s+/g,'').toLowerCase()}
function mkDrug(d,i){let s=n(d.specText||d.strengthMg),c=n(d.concentration)||10;return{id:'d'+i,name:d.drugName||d.name,strength:s,price:n(d.price),conc:c,revol:n(d.reconstitutionVolumeText)||s/c,solvent:d.solvent||'0.9% NaCl 100 mL',share:!norm(d.shareable).includes('notshareable')&&!norm(d.shareable).includes('不共享'),shareText:d.shareable||'Shareable',rules:d.rules||''}}
function headers(row){return row.map(h=>norm(h))}
function val(o,ks){for(const k of ks){if(o[k]!=null&&o[k]!=='')return o[k]}return''}
function parseTable(text){let lines=String(text||'').trim().split(/\r?\n/).filter(Boolean);if(!lines.length)return[];let sep=lines[0].includes('\t')?'\t':',';let h=headers(lines[0].split(sep));return lines.slice(1).map((line,i)=>{let cells=line.split(sep).map(x=>x.trim());let o={row:i+2};h.forEach((k,j)=>o[k]=cells[j]||'');let drug=val(o,['drugname','drug','药品名称','药品']);let dose=n(val(o,['orderdosemg','dose','医嘱剂量mg','剂量']));let strength=n(val(o,['vialstrengthmg','strength','药品规格mg','规格']));let route=val(o,['route','给药途径','用法'])||'IV infusion';let name=val(o,['patientname','patient','患者','患者姓名'])||'Patient '+(i+1);let batch=val(o,['batch','批次'])||'Batch 1';let d=findDrug(drug,strength);if(!d&&drug){d={id:'u'+Date.now()+i,name:drug,strength:strength||100,price:n(val(o,['pricepervial','price','药品单价']))||0,conc:n(val(o,['reconstitutedconcentrationmg/ml','concentration','复溶后浓度mg/ml']))||10,revol:(strength||100)/(n(val(o,['reconstitutedconcentrationmg/ml','concentration']))||10),solvent:'0.9% NaCl 100 mL',share:true,shareText:'Temporary rule'};drugs.push(d)}return{patient:name,drugName:drug,dose,route,batch,ward:val(o,['ward','病区']),bed:val(o,['bed','床号']),time:val(o,['preparationtime','配置时间'])||'09:00',infusion:val(o,['infusiontime','输注时间'])||'10:00',baseline:n(val(o,['dispensedvials','实际分配瓶数']))||Math.ceil(dose/(d?.strength||strength||100)),drug:d}}).filter(x=>x.drug&&x.dose>0)}
function findDrug(name,strength){let q=norm(name);return drugs.find(d=>(norm(d.name).includes(q)||q.includes(norm(d.name))||q.includes(norm(d.name).replace('injection','').replace('for','')))&&(!strength||Math.abs(d.strength-strength)<.01))}
function calculate(){plans=[];let groups={};orders.forEach(o=>{let iv=norm(o.route).includes('ivinjection')||norm(o.route).includes('ivpush');if(!o.drug.share||iv)return;let k=o.drug.id+'|'+o.batch;(groups[k]||(groups[k]=[])).push(o)});Object.values(groups).forEach(list=>{list.sort((a,b)=>String(a.batch).localeCompare(String(b.batch))||a.time.localeCompare(b.time));let d=list[0].drug,vials=[];list.forEach(o=>{let left=o.dose;while(left>0){let vial=vials.find(v=>v.remain>0.0001);if(!vial){vial={no:vials.length+1,orders:[],remain:d.strength};vials.push(vial)}let use=Math.min(left,vial.remain);vial.orders.push({order:o,mg:use,before:vial.remain,after:vial.remain-use});vial.remain-=use;left-=use}});let baseline=list.reduce((s,o)=>s+o.baseline,0),after=vials.length,saved=Math.max(0,baseline-after);plans.push({id:d.id+'|'+list[0].batch,drug:d,batch:list[0].batch,orders:list,vials,baseline,after,saved,amount:saved*d.price})});plans.sort((a,b)=>b.saved-a.saved||a.batch.localeCompare(b.batch))}
function totals(){return plans.reduce((a,p)=>{a.before+=p.baseline;a.after+=p.after;a.saved+=p.saved;a.amount+=p.amount;a.pat+=p.orders.length;return a},{before:0,after:0,saved:0,amount:0,pat:0})}
function qs(s){return document.querySelector(s)}
function waste(){let opened=0,remain=0;plans.forEach(p=>p.vials.forEach(v=>{opened+=p.drug.strength;remain+=v.remain}));return opened?remain/opened:0}
function render(){calculate();let tot=totals();qs('#savedAmount').textContent=orders.length?money(tot.amount):'-';qs('#shareRate').textContent=orders.length&&tot.before?Math.round((tot.saved/tot.before)*100)+'%':'-';qs('#wasteRate').textContent=orders.length?Math.round(waste()*100)+'%':'-';qs('#patientCount').textContent=orders.length?new Set(orders.map(o=>o.patient)).size:'-';renderSummary();renderTasks();renderBatch();renderInstructions();renderAnalytics();renderHistory();renderDrugs()}
function cards(a){return a.map(x=>`<div class="real-world-card"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}
function renderSummary(){qs('#importMetrics').innerHTML=orders.length?cards([['Drugs',new Set(orders.map(o=>o.drug.name)).size],['Patients',new Set(orders.map(o=>o.patient)).size],['Baseline Vials',r(totals().before)],['Optimized Vials',r(totals().after)],['Saved Vials',r(totals().saved)]]):'';qs('#importSummaryRows').innerHTML=orders.length?plans.map(p=>`<tr><td>${p.drug.name}</td><td>${p.orders.length}</td><td>${r(p.baseline)}</td><td>${r(p.after)}</td><td>${r(p.saved)}</td><td><span class="ok">Shareable</span></td></tr>`).join(''):`<tr><td colspan="6">${T.empty}</td></tr>`}
function renderTasks(){qs('#runStatus').textContent=orders.length?'Calculated':'Pending Import';qs('#drugTasks').innerHTML=plans.length?plans.map(p=>`<button class="task-card drug-task ${selectedDrug===p.id?'selected':''}" data-id="${p.id}"><h4>${p.drug.name}</h4><div class="meta-row"><span>${p.batch}</span><span>${p.orders.length} patients</span><span>${r(p.saved)} vials saved</span><span>${money(p.amount)}</span></div></button>`).join(''):`<div class="task-card"><h4>${T.empty}</h4></div>`}
function renderBatch(){let batches=['all',...new Set(plans.map(p=>p.batch))];qs('#currentBatch').innerHTML=batches.map(b=>`<option value="${b}">${b==='all'?T.batchAll:b}</option>`).join('');let cur=qs('#currentBatch').value||'all';qs('#batchTimeline').innerHTML=plans.filter(p=>cur==='all'||p.batch===cur).map(p=>{let rem=p.vials.reduce((s,v)=>s+v.remain,0);return`<tr><td>${p.batch}</td><td>${p.drug.name}</td><td>${p.orders.length}</td><td>${p.after} vials</td><td>${rem>0?'Yes':'No'}</td><td>${r(rem)} mg</td><td>Today 17:00</td></tr>`}).join('')||`<tr><td colspan="7">${T.empty}</td></tr>`}
function renderInstructions(){let p=plans.find(x=>x.id===selectedDrug)||plans[0];if(!p){qs('#instructionRows').innerHTML=`<tr><td colspan="5">${T.select}</td></tr>`;return}selectedDrug=p.id;qs('#instructionTitle').textContent=`${p.drug.name} (${p.drug.strength} mg/vial; reconstitute with ${r(p.drug.revol)} mL; ${r(p.drug.conc)} mg/mL) · Post-sharing Preparation Volume Conversion`;let by=new Map();p.vials.forEach(v=>v.orders.forEach(seg=>{let e=by.get(seg.order.patient)||{o:seg.order,parts:[],notes:[]};let ml=seg.mg/p.drug.conc;let first=Math.abs(seg.before-p.drug.strength)<.001;if(seg.mg>=p.drug.strength-.001)e.parts.push(`whole vial ${v.no}`);else e.parts.push(`${first?'shared vial':'reuse shared vial'} ${v.no} withdraw ${r(ml)} mL`);e.notes.push(`${first?'shared vial':'reuse shared vial'} ${v.no}: withdraw ${r(ml)} mL, residual ${r(seg.after/p.drug.conc)} mL`);by.set(seg.order.patient,e)}));qs('#instructionRows').innerHTML=[...by.values()].map(e=>`<tr><td>${e.o.patient}</td><td>${r(e.o.dose)} mg</td><td>${e.parts.join(' + ')}</td><td>${p.drug.solvent}</td><td>${e.o.batch}, ${e.o.ward||''} ${e.o.bed||''}, ${e.o.route}; ${e.notes.join('; ')}</td></tr>`).join('')}
function renderAnalytics(){let t=totals();qs('#analyticsCards').innerHTML=orders.length?[['Saved Vials',r(t.saved)+' vials'],['Savings',money(t.amount)],['Shareable Drugs',plans.length+' drugs'],['Waste Rate',Math.round(waste()*100)+'%']].map(x=>`<div class="analytics-card"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join(''):'<div class="analytics-card">No analytics yet.</div>'}
function renderHistory(){qs('#historyCount').textContent=history.length+' records';qs('#historyRows').innerHTML=history.length?history.map(h=>`<tr><td>${h.time}</td><td>${h.drugs}</td><td>${h.patients}</td><td>${h.before}</td><td>${h.after}</td><td>${h.saved}</td><td>${h.amount}</td><td><button class="table-action" data-view="${h.id}">View Details</button><button class="table-action danger" data-del="${h.id}">Delete</button></td></tr>`).join(''):`<tr><td colspan="8">${T.historyEmpty}</td></tr>`;let h=history.find(x=>x.id===expanded);qs('#historyDetail').innerHTML=h?`<div class="history-section"><h4>Drug Summary</h4>${h.detail}</div>`:''}
function renderDrugs(){let q=norm(qs('#drugKnowledgeSearch')?.value||'');let list=q?drugs.filter(d=>norm(d.name+d.solvent+d.shareText).includes(q)):[];qs('#drugKnowledgeCount').textContent=q?`Total ${drugs.length} drugs; showing ${list.length} drugs`:`Total ${drugs.length} drugs`;qs('#drugKnowledgeRows').innerHTML=q?list.map(d=>`<tr><td>${d.name}</td><td>${d.strength} mg</td><td>${d.conc} mg/mL</td><td>${r(d.revol)} mL</td><td>${d.solvent}</td><td>Pending</td><td>Pending</td><td>${d.shareText}</td><td>Demo</td><td>${d.rules||''}</td></tr>`).join(''):'<tr><td colspan="10">Enter a drug name to search.</td></tr>'}
function loadSample(){qs('#orderPaste').value='Patient Name,Drug Name,Order Dose (mg),Vial Strength (mg),Price per Vial,Reconstituted Concentration (mg/mL),Route,Preparation Time,Infusion Time,Ward,Bed,Batch,Dispensed Vials\nPatient A,Bevacizumab Injection,60,100,1180,10,IV infusion,09:00,10:00,Ward 1,Bed 1,Batch 1,1\nPatient B,Bevacizumab Injection,35,100,1180,10,IV infusion,09:05,10:20,Ward 1,Bed 2,Batch 1,1\nPatient C,Gemcitabine Hydrochloride for Injection,1200,1000,680,40,IV infusion,10:00,11:00,Ward 2,Bed 3,Batch 2,2\nPatient D,Gemcitabine Hydrochloride for Injection,780,1000,680,40,IV infusion,10:05,11:10,Ward 2,Bed 4,Batch 2,1'}
function saveHistory(){if(!plans.length){alert('No sharable plan to archive.');return}let t=totals(),h={id:Date.now(),time:new Date().toLocaleString('en-US'),drugs:plans.map(p=>p.drug.name).join(', '),patients:new Set(orders.map(o=>o.patient)).size,before:r(t.before),after:r(t.after),saved:r(t.saved),amount:money(t.amount),detail:plans.map(p=>`${p.drug.name}: ${p.orders.length} patients, baseline ${r(p.baseline)} vials, optimized ${r(p.after)} vials, saved ${r(p.saved)} vials`).join('<br>')};history.unshift(h);localStorage.setItem('dosepilot_history_en',JSON.stringify(history));render();alert(T.saved)}
qs('#loadSampleOrders')?.addEventListener('click',loadSample);qs('#importOrders')?.addEventListener('click',()=>{orders=parseTable(qs('#orderPaste').value);selectedDrug=null;render()});qs('#clearOrders')?.addEventListener('click',()=>{orders=[];plans=[];selectedDrug=null;qs('#orderPaste').value='';render()});qs('#drugTasks')?.addEventListener('click',e=>{let b=e.target.closest('[data-id]');if(b){selectedDrug=b.dataset.id;render()}});qs('#currentBatch')?.addEventListener('change',renderBatch);qs('#confirmPlan')?.addEventListener('click',saveHistory);qs('#historyRows')?.addEventListener('click',e=>{if(e.target.dataset.view){expanded=Number(e.target.dataset.view);render()}if(e.target.dataset.del){history=history.filter(h=>h.id!==Number(e.target.dataset.del));localStorage.setItem('dosepilot_history_en',JSON.stringify(history));render()}});qs('#drugKnowledgeSearch')?.addEventListener('input',renderDrugs);qs('#printLabels')?.addEventListener('click',()=>print());document.querySelectorAll('[data-file-trigger]').forEach(b=>b.addEventListener('click',()=>qs('#'+b.dataset.fileTrigger).click()));qs('#orderFile')?.addEventListener('change',async e=>{let f=e.target.files[0];if(f){qs('#orderFileName').textContent=f.name;qs('#orderPaste').value=await f.text();orders=parseTable(qs('#orderPaste').value);render()}});qs('#drugKnowledgeFile')?.addEventListener('change',e=>{let f=e.target.files[0];if(f)qs('#drugKnowledgeFileName').textContent=f.name});render();
