const T={empty:'请导入当日医嘱后查看结果。',select:'请先在“今日共享任务”中选择药品。',batchAll:'全部批次',historyEmpty:'暂无历史记录。',saved:'已保存当前方案。'};
let drugs=(window.DRUG_KNOWLEDGE_SEED||[]).map((d,i)=>mkDrug(d,i));
let orders=[],plans=[],selectedDrug=null,history=JSON.parse(localStorage.getItem('dosepilot_history_zh')||'[]'),expanded=null;
function n(v){return Number(String(v||'').match(/\d+(\.\d+)?/)?.[0]||0)}
function r(v){return Number(v||0).toFixed(2).replace(/\.00$/,'').replace(/0$/,'')}
function money(v){return '¥'+Math.round(v||0).toLocaleString('zh-CN')}
function norm(v){return String(v||'').replace(/[（(].*?[）)]/g,'').replace(/\s+/g,'').toLowerCase()}
function mkDrug(d,i){let s=n(d.specText||d.strengthMg),c=n(d.concentration)||10;return{id:'d'+i,name:d.drugName||d.name,strength:s,price:n(d.price),conc:c,revol:n(d.reconstitutionVolumeText)||s/c,solvent:d.solvent||'0.9% NaCl 100 mL',share:!norm(d.shareable).includes('不共享')&&!norm(d.shareable).includes('notshareable'),shareText:d.shareable||'可共享',rules:d.rules||''}}
function headers(row){return row.map(h=>norm(h))}
function val(o,ks){for(const k of ks){if(o[k]!=null&&o[k]!=='')return o[k]}return''}
function parseTable(text){let lines=String(text||'').trim().split(/\r?\n/).filter(Boolean);if(!lines.length)return[];let sep=lines[0].includes('\t')?'\t':',';let h=headers(lines[0].split(sep));return lines.slice(1).map((line,i)=>{let cells=line.split(sep).map(x=>x.trim());let o={row:i+2};h.forEach((k,j)=>o[k]=cells[j]||'');let drug=val(o,['药品名称','药品','drugname']);let dose=n(val(o,['医嘱剂量mg','剂量','orderdosemg','dose']));let strength=n(val(o,['药品规格mg','规格','vialstrengthmg','strength']));let route=val(o,['给药途径','用法','给药方式','途径','route'])||'静脉滴注';let name=val(o,['患者','患者姓名','patient','patientname'])||'患者'+(i+1);let batch=val(o,['批次','batch'])||'第一批';let d=findDrug(drug,strength);if(!d&&drug){d={id:'u'+Date.now()+i,name:drug,strength:strength||100,price:n(val(o,['药品单价','单价','pricepervial']))||0,conc:n(val(o,['复溶后浓度mg/ml','浓度','reconstitutedconcentrationmg/ml']))||10,revol:(strength||100)/(n(val(o,['复溶后浓度mg/ml','浓度']))||10),solvent:'0.9% NaCl 100 mL',share:true,shareText:'临时规则'};drugs.push(d)}return{patient:name,drugName:drug,dose,route,batch,ward:val(o,['病区','ward']),bed:val(o,['床号','bed']),time:val(o,['配置时间','preparationtime'])||'09:00',infusion:val(o,['输注时间','infusiontime'])||'10:00',baseline:n(val(o,['实际分配瓶数','dispensedvials']))||Math.ceil(dose/(d?.strength||strength||100)),drug:d}}).filter(x=>x.drug&&x.dose>0)}
function findDrug(name,strength){let q=norm(name);return drugs.find(d=>(norm(d.name).includes(q)||q.includes(norm(d.name))||q.includes(norm(d.name).replace('注射用','').replace('注射液','')))&&(!strength||Math.abs(d.strength-strength)<.01))}
function calculate(){plans=[];let groups={};orders.forEach(o=>{let iv=norm(o.route).includes('静脉注射');if(!o.drug.share||iv)return;let k=o.drug.id+'|'+o.batch;(groups[k]||(groups[k]=[])).push(o)});Object.values(groups).forEach(list=>{list.sort((a,b)=>String(a.batch).localeCompare(String(b.batch),'zh-CN')||a.time.localeCompare(b.time));let d=list[0].drug,vials=[];list.forEach(o=>{let left=o.dose;while(left>0){let vial=vials.find(v=>v.remain>0.0001);if(!vial){vial={no:vials.length+1,orders:[],remain:d.strength};vials.push(vial)}let use=Math.min(left,vial.remain);vial.orders.push({order:o,mg:use,before:vial.remain,after:vial.remain-use});vial.remain-=use;left-=use}});let baseline=list.reduce((s,o)=>s+o.baseline,0),after=vials.length,saved=Math.max(0,baseline-after);plans.push({id:d.id+'|'+list[0].batch,drug:d,batch:list[0].batch,orders:list,vials,baseline,after,saved,amount:saved*d.price})});plans.sort((a,b)=>b.saved-a.saved||a.batch.localeCompare(b.batch,'zh-CN'))}
function totals(){return plans.reduce((a,p)=>{a.before+=p.baseline;a.after+=p.after;a.saved+=p.saved;a.amount+=p.amount;a.pat+=p.orders.length;return a},{before:0,after:0,saved:0,amount:0,pat:0})}
function render(){calculate();let tot=totals();qs('#savedAmount').textContent=orders.length?money(tot.amount):'-';qs('#shareRate').textContent=orders.length&&tot.after?Math.round((tot.saved/tot.before)*100)+'%':'-';qs('#wasteRate').textContent=orders.length?Math.round(waste()*100)+'%':'-';qs('#patientCount').textContent=orders.length?new Set(orders.map(o=>o.patient)).size:'-';renderSummary();renderTasks();renderBatch();renderInstructions();renderAnalytics();renderHistory();renderDrugs()}
function waste(){let opened=0,remain=0;plans.forEach(p=>p.vials.forEach(v=>{opened+=p.drug.strength;remain+=v.remain}));return opened?remain/opened:0}
function qs(s){return document.querySelector(s)}
function renderSummary(){qs('#importMetrics').innerHTML=orders.length?cards([['药品',new Set(orders.map(o=>o.drug.name)).size],['患者',new Set(orders.map(o=>o.patient)).size],['共享前瓶数',r(totals().before)],['共享后瓶数',r(totals().after)],['节约瓶数',r(totals().saved)]]):'';qs('#importSummaryRows').innerHTML=orders.length?plans.map(p=>`<tr><td>${p.drug.name}</td><td>${p.orders.length}</td><td>${r(p.baseline)}</td><td>${r(p.after)}</td><td>${r(p.saved)}</td><td><span class="ok">可共享</span></td></tr>`).join(''):`<tr><td colspan="6">${T.empty}</td></tr>`}
function cards(a){return a.map(x=>`<div class="real-world-card"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}
function renderTasks(){qs('#runStatus').textContent=orders.length?'已计算':'待导入';qs('#drugTasks').innerHTML=plans.length?plans.map(p=>`<button class="task-card drug-task ${selectedDrug===p.id?'selected':''}" data-id="${p.id}"><h4>${p.drug.name}</h4><div class="meta-row"><span>${p.batch}</span><span>${p.orders.length}人</span><span>节约${r(p.saved)}瓶</span><span>${money(p.amount)}</span></div></button>`).join(''):`<div class="task-card"><h4>${T.empty}</h4></div>`}
function renderBatch(){let batches=['all',...new Set(plans.map(p=>p.batch))];qs('#currentBatch').innerHTML=batches.map(b=>`<option value="${b}">${b==='all'?T.batchAll:b}</option>`).join('');let cur=qs('#currentBatch').value||'all';let rows=plans.filter(p=>cur==='all'||p.batch===cur).map(p=>{let rem=p.vials.reduce((s,v)=>s+v.remain,0);return`<tr><td>${p.batch}</td><td>${p.drug.name}</td><td>${p.orders.length}</td><td>${p.after}瓶</td><td>${rem>0?'有':'无'}</td><td>${r(rem)} mg</td><td>当日 17:00</td></tr>`}).join('');qs('#batchTimeline').innerHTML=rows||`<tr><td colspan="7">${T.empty}</td></tr>`}
function renderInstructions(){let p=plans.find(x=>x.id===selectedDrug)||plans[0];if(!p){qs('#instructionRows').innerHTML=`<tr><td colspan="5">${T.select}</td></tr>`;return}selectedDrug=p.id;qs('#instructionTitle').textContent=`${p.drug.name}（${p.drug.strength} mg/瓶；复溶${r(p.drug.revol)} mL；${r(p.drug.conc)} mg/mL） · 共享后药品调配量自动换算`;let by=new Map();p.vials.forEach(v=>v.orders.forEach(seg=>{let e=by.get(seg.order.patient)||{o:seg.order,parts:[],notes:[]};let ml=seg.mg/p.drug.conc;let first=Math.abs(seg.before-p.drug.strength)<.001;if(seg.mg>=p.drug.strength-.001)e.parts.push(`整瓶${v.no}`);else e.parts.push(`${first?'共享瓶':'续用共享瓶'}${v.no}抽取${r(ml)} mL`);e.notes.push(`${first?'共享瓶':'续用共享瓶'}${v.no}：抽取${r(ml)} mL，余${r(seg.after/p.drug.conc)} mL`);by.set(seg.order.patient,e)}));qs('#instructionRows').innerHTML=[...by.values()].map(e=>`<tr><td>${e.o.patient}</td><td>${r(e.o.dose)} mg</td><td>${e.parts.join(' + ')}</td><td>${p.drug.solvent}</td><td>${e.o.batch}，${e.o.ward||''}${e.o.bed||''}，${e.o.route}；${e.notes.join('；')}</td></tr>`).join('')}
function renderAnalytics(){let t=totals();qs('#analyticsCards').innerHTML=orders.length?[['节约瓶数',r(t.saved)+'瓶'],['节约金额',money(t.amount)],['共享药品',plans.length+'种'],['浪费率',Math.round(waste()*100)+'%']].map(x=>`<div class="analytics-card"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join(''):'<div class="analytics-card">暂无统计。</div>'}
function renderHistory(){qs('#historyCount').textContent=history.length+' 条记录';qs('#historyRows').innerHTML=history.length?history.map(h=>`<tr><td>${h.time}</td><td>${h.drugs}</td><td>${h.patients}</td><td>${h.before}</td><td>${h.after}</td><td>${h.saved}</td><td>${h.amount}</td><td><button class="table-action" data-view="${h.id}">查看详情</button><button class="table-action danger" data-del="${h.id}">删除</button></td></tr>`).join(''):`<tr><td colspan="8">${T.historyEmpty}</td></tr>`;let h=history.find(x=>x.id===expanded);qs('#historyDetail').innerHTML=h?`<div class="history-section"><h4>药品汇总</h4>${h.detail}</div>`:''}
function renderDrugs(){let q=norm(qs('#drugKnowledgeSearch')?.value||'');let list=q?drugs.filter(d=>norm(d.name+d.solvent+d.shareText).includes(q)):[];qs('#drugKnowledgeCount').textContent=q?`共 ${drugs.length} 种，当前显示 ${list.length} 种`:`共 ${drugs.length} 种药品`;qs('#drugKnowledgeRows').innerHTML=q?list.map(d=>`<tr><td>${d.name}</td><td>${d.strength} mg</td><td>${d.conc} mg/mL</td><td>${r(d.revol)} mL</td><td>${d.solvent}</td><td>待维护</td><td>待维护</td><td>${d.shareText}</td><td>演示</td><td>${d.rules||''}</td></tr>`).join(''):'<tr><td colspan="10">请输入药品名称进行查询。</td></tr>'}
function loadSample(){qs('#orderPaste').value='患者,药品名称,医嘱剂量mg,药品规格mg,药品单价,复溶后浓度mg/mL,给药途径,配置时间,输注时间,病区,床号,批次,实际分配瓶数\nA患者,贝伐珠单抗注射液,60,100,1180,10,静脉滴注,09:00,10:00,一病区,1床,第一批,1\nB患者,贝伐珠单抗注射液,35,100,1180,10,静脉滴注,09:05,10:20,一病区,2床,第一批,1\nC患者,注射用盐酸吉西他滨,1200,1000,680,40,静脉滴注,10:00,11:00,二病区,3床,第二批,2\nD患者,注射用盐酸吉西他滨,780,1000,680,40,静脉滴注,10:05,11:10,二病区,4床,第二批,1'}
function saveHistory(){if(!plans.length){alert('当前没有可归档的共享方案。');return}let t=totals(),h={id:Date.now(),time:new Date().toLocaleString('zh-CN'),drugs:plans.map(p=>p.drug.name).join('、'),patients:new Set(orders.map(o=>o.patient)).size,before:r(t.before),after:r(t.after),saved:r(t.saved),amount:money(t.amount),detail:plans.map(p=>`${p.drug.name}：${p.orders.length}人，共享前${r(p.baseline)}瓶，共享后${r(p.after)}瓶，节约${r(p.saved)}瓶`).join('<br>')};history.unshift(h);localStorage.setItem('dosepilot_history_zh',JSON.stringify(history));render();alert(T.saved)}
qs('#loadSampleOrders')?.addEventListener('click',loadSample);qs('#importOrders')?.addEventListener('click',()=>{orders=parseTable(qs('#orderPaste').value);selectedDrug=null;render()});qs('#clearOrders')?.addEventListener('click',()=>{orders=[];plans=[];selectedDrug=null;qs('#orderPaste').value='';render()});qs('#drugTasks')?.addEventListener('click',e=>{let b=e.target.closest('[data-id]');if(b){selectedDrug=b.dataset.id;render()}});qs('#currentBatch')?.addEventListener('change',renderBatch);qs('#confirmPlan')?.addEventListener('click',saveHistory);qs('#historyRows')?.addEventListener('click',e=>{if(e.target.dataset.view){expanded=Number(e.target.dataset.view);render()}if(e.target.dataset.del){history=history.filter(h=>h.id!==Number(e.target.dataset.del));localStorage.setItem('dosepilot_history_zh',JSON.stringify(history));render()}});qs('#drugKnowledgeSearch')?.addEventListener('input',renderDrugs);qs('#askAi')?.addEventListener('click',()=>{qs('#aiAnswer').textContent=plans.length?`当前方案按批次优先分配，预计节约${r(totals().saved)}瓶，节约金额${money(totals().amount)}。系统将同药同规格患者合并到共享瓶，并在调配指令中显示每瓶余液去向。`:'请先导入医嘱。'});qs('#printLabels')?.addEventListener('click',()=>print());document.querySelectorAll('[data-file-trigger]').forEach(b=>b.addEventListener('click',()=>qs('#'+b.dataset.fileTrigger).click()));qs('#orderFile')?.addEventListener('change',async e=>{let f=e.target.files[0];if(f){qs('#orderPaste').value=await f.text();orders=parseTable(qs('#orderPaste').value);render()}});render();
