window.DRUG_KNOWLEDGE_SEED = [
  {
    "drugName": "伊匹木单抗注射液",
    "englishName": "",
    "specText": "50mg",
    "drugVolumeText": "10ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "盐酸伊立替康注射液",
    "englishName": "",
    "specText": "100mg",
    "drugVolumeText": "5ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "盐酸伊立替康注射液",
    "englishName": "",
    "specText": "40mg",
    "drugVolumeText": "2ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "盐酸伊立替康脂质体注射液",
    "englishName": "",
    "specText": "43mg",
    "drugVolumeText": "10ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "优替德隆注射液",
    "englishName": "",
    "specText": "50mg",
    "drugVolumeText": "5ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "依托泊苷注射液",
    "englishName": "",
    "specText": "100mg",
    "drugVolumeText": "5ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "信迪利单抗注射液",
    "englishName": "",
    "specText": "100mg",
    "drugVolumeText": "10ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "利妥昔单抗注射液",
    "englishName": "",
    "specText": "100mg",
    "drugVolumeText": "10ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "利妥昔单抗注射液",
    "englishName": "",
    "specText": "500mg",
    "drugVolumeText": "50ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "卡度尼利单抗注射液",
    "englishName": "",
    "specText": "125mg",
    "drugVolumeText": "10ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "卡铂注射液 ",
    "englishName": "",
    "specText": "100mg",
    "drugVolumeText": "10ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "卡铂注射液 ",
    "englishName": "",
    "specText": "150mg",
    "drugVolumeText": "15ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "培门冬酶注射液",
    "englishName": "",
    "specText": "3750mg",
    "drugVolumeText": "5ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "塞替派注射液",
    "englishName": "",
    "specText": "10mg",
    "drugVolumeText": "1ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用盐酸多柔比星",
    "englishName": "",
    "specText": "10mg",
    "drugVolumeText": "10ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "多柔比星脂质体注射液",
    "englishName": "",
    "specText": "10mg",
    "drugVolumeText": "10ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "多柔比星脂质体注射液",
    "englishName": "",
    "specText": "20mg",
    "drugVolumeText": "10ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "多西他赛注射液",
    "englishName": "",
    "specText": "20mg",
    "drugVolumeText": "1ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "多西他赛注射液",
    "englishName": "",
    "specText": "20mg",
    "drugVolumeText": "0.5ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "帕博利珠单抗注射液",
    "englishName": "",
    "specText": "100mg",
    "drugVolumeText": "4ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "斯鲁利单抗注射液",
    "englishName": "",
    "specText": "100mg",
    "drugVolumeText": "10ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "替尼泊苷注射液",
    "englishName": "",
    "specText": "50mg",
    "drugVolumeText": "5ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "氟尿嘧啶注射液",
    "englishName": "",
    "specText": "250mg",
    "drugVolumeText": "10ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "氟尿嘧啶注射液",
    "englishName": "",
    "specText": "500mg",
    "drugVolumeText": "10ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "泽贝妥单抗注射液",
    "englishName": "Zuberitamab",
    "specText": "100mg",
    "drugVolumeText": "10ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "特瑞普利单抗注射液",
    "englishName": "",
    "specText": "80mg",
    "drugVolumeText": "2ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "甲氨蝶呤注射液",
    "englishName": "",
    "specText": "1000mg",
    "drugVolumeText": "10ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "甲氨蝶呤注射液",
    "englishName": "",
    "specText": "50mg",
    "drugVolumeText": "2ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "盐酸米托蒽醌脂质体注射液",
    "englishName": "",
    "specText": "10mg",
    "drugVolumeText": "10ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "紫杉醇注射液",
    "englishName": "",
    "specText": "30mg",
    "drugVolumeText": "5ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "5%葡萄糖注射液",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "纳武利尤单抗注射液",
    "englishName": "",
    "specText": "100mg",
    "drugVolumeText": "10ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "纳武利尤单抗注射液",
    "englishName": "",
    "specText": "40mg",
    "drugVolumeText": "4ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "艾立布林注射液",
    "englishName": "",
    "specText": "1mg",
    "drugVolumeText": "2ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "西妥昔单抗注射液",
    "englishName": "",
    "specText": "100mg",
    "drugVolumeText": "20ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "贝伐珠单抗注射液",
    "englishName": "",
    "specText": "100mg",
    "drugVolumeText": "4ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "贝伐珠单抗注射液",
    "englishName": "",
    "specText": "400mg",
    "drugVolumeText": "16ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "达雷妥尤单抗注射液",
    "englishName": "",
    "specText": "400mg",
    "drugVolumeText": "20ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "雷莫西尤单抗注射液",
    "englishName": "",
    "specText": "500mg",
    "drugVolumeText": "50ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "顺铂注射液",
    "englishName": "",
    "specText": "30mg",
    "drugVolumeText": "6ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "顺铂注射液",
    "englishName": "",
    "specText": "50mg",
    "drugVolumeText": "50ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "高三尖杉酯碱注射液",
    "englishName": "",
    "specText": "1mg",
    "drugVolumeText": "1ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "奥沙利铂甘露醇注射液",
    "englishName": "",
    "specText": "50mg",
    "drugVolumeText": "100ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "白消安注射液",
    "englishName": "",
    "specText": "60mg",
    "drugVolumeText": "10ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "酒石酸长春瑞滨注射液",
    "englishName": "",
    "specText": "10mg",
    "drugVolumeText": "1ml",
    "requiresReconstitution": "否",
    "concentration": "",
    "reconstitutionSolvent": "",
    "reconstitutionVolumeText": "",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用紫杉醇脂质体",
    "englishName": "",
    "specText": "30mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "3 mg/ml",
    "reconstitutionSolvent": "5%葡萄糖注射液",
    "reconstitutionVolumeText": "10ml",
    "reconstitutedStabilityText": "",
    "solvent": " 250-500ml 5%葡萄糖溶液",
    "dilutedStabilityText": "室温(25℃)和室内灯光下 24 小时",
    "shareable": "可共享",
    "rules": "本品只能用 5%葡萄糖注射液溶解和稀释，不可用生理盐水或其他溶液溶解、稀释，以免发生脂质体聚集。"
  },
  {
    "drugName": "注射用三氧化二砷",
    "englishName": "",
    "specText": "5mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "2.5mg/ml",
    "reconstitutionSolvent": "0.9%氯化钠",
    "reconstitutionVolumeText": "2ml",
    "reconstitutedStabilityText": "",
    "solvent": "5%葡萄糖注射液USP或0.9%氯化钠注射液 500ml",
    "dilutedStabilityText": "储存在20-25℃；波动在15-30℃；不要冻存",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用丝裂霉素",
    "englishName": "",
    "specText": "10mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "0.5mg/ml",
    "reconstitutionSolvent": "无菌注射用水",
    "reconstitutionVolumeText": "20ml",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "避免超过40℃",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用亮丙瑞林微球",
    "englishName": "",
    "specText": "11.25mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "11.25 mg/ml",
    "reconstitutionSolvent": "随药附带专用注射用溶剂",
    "reconstitutionVolumeText": "1ml",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "低于25℃避光",
    "shareable": "不共享，皮下注射，一般整支使用",
    "rules": ""
  },
  {
    "drugName": "注射用伊尼妥单抗",
    "englishName": "",
    "specText": "50mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "20 mg/ml",
    "reconstitutionSolvent": "无菌注射用水",
    "reconstitutionVolumeText": "2.5ml",
    "reconstitutedStabilityText": "立即使用",
    "solvent": " 250 mL 0.9% 氯化钠注射液，禁用5%葡萄糖注射液",
    "dilutedStabilityText": "2-8℃避光干燥保存",
    "shareable": "可共享",
    "rules": "为防止微生物污染，药品溶解后的药液应立即使用；严禁剧烈振摇"
  },
  {
    "drugName": "注射用伊达比星",
    "englishName": "",
    "specText": "10mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "1 mg/ml",
    "reconstitutionSolvent": "注射用水（USP）",
    "reconstitutionVolumeText": "10ml",
    "reconstitutedStabilityText": "",
    "solvent": "无",
    "dilutedStabilityText": "15-30℃避光",
    "shareable": "不共享，仅用于静脉注射",
    "rules": ""
  },
  {
    "drugName": "注射用盐酸伊达比星",
    "englishName": "",
    "specText": "5mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "1 mg/ml",
    "reconstitutionSolvent": "无菌注射用水",
    "reconstitutionVolumeText": "5ml",
    "reconstitutedStabilityText": "",
    "solvent": "无",
    "dilutedStabilityText": "存放在15-30℃的受控室温下，并避光。",
    "shareable": "不共享，仅用于静脉注射",
    "rules": ""
  },
  {
    "drugName": "注射用盐酸博来霉素",
    "englishName": "",
    "specText": "15mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "3mg/ml",
    "reconstitutionSolvent": "无菌注射用水、0.9%氯化钠注射液",
    "reconstitutionVolumeText": "5ml",
    "reconstitutedStabilityText": "",
    "solvent": "0.9%氯化钠注射液",
    "dilutedStabilityText": "室温下稳定放置24 h",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用卡铂",
    "englishName": "",
    "specText": "50mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "10 mg/ml",
    "reconstitutionSolvent": "5％葡萄糖溶液",
    "reconstitutionVolumeText": "5ml",
    "reconstitutedStabilityText": "",
    "solvent": "5%葡萄糖溶液或0.9%氯化钠注射液 100ml以上",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用卡非佐米",
    "englishName": "",
    "specText": "60mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "2 mg/ml",
    "reconstitutionSolvent": "无菌注射用水",
    "reconstitutionVolumeText": "29ml",
    "reconstitutedStabilityText": "",
    "solvent": " 50 mL 或 100 mL 5% 葡萄糖注射液",
    "dilutedStabilityText": "2-8℃稳定24小时；15-30℃稳定4小时",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用司妥昔单抗",
    "englishName": "",
    "specText": "400mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "20 mg/ml",
    "reconstitutionSolvent": "无菌注射用水",
    "reconstitutionVolumeText": "20ml",
    "reconstitutedStabilityText": "不得超过 2 小时",
    "solvent": "250 mL 5% 葡萄糖",
    "dilutedStabilityText": "配制后 6 小时内完成给药。",
    "shareable": "可共享",
    "rules": "不含防腐剂"
  },
  {
    "drugName": "注射用盐酸吉西他滨",
    "englishName": "",
    "specText": "1000mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "38 mg/ml",
    "reconstitutionSolvent": "0.9%氯化钠溶液",
    "reconstitutionVolumeText": "25ml",
    "reconstitutedStabilityText": "",
    "solvent": "0.9%氯化钠注射液",
    "dilutedStabilityText": "20°-25℃稳定24h，不要冷藏",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用盐酸吉西他滨",
    "englishName": "",
    "specText": "200mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "38 mg/ml",
    "reconstitutionSolvent": "0.9%氯化钠溶液",
    "reconstitutionVolumeText": "5ml",
    "reconstitutedStabilityText": "",
    "solvent": "0.9%氯化钠注射液",
    "dilutedStabilityText": "20°-25℃稳定24h，不要冷藏",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用盐酸吡柔比星",
    "englishName": "",
    "specText": "10mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "1 mg/ml",
    "reconstitutionSolvent": "5%葡萄糖注射液或注射用水",
    "reconstitutionVolumeText": "10ml",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "室温6小时",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用地加瑞克",
    "englishName": "",
    "specText": "120mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "40 mg/ml",
    "reconstitutionSolvent": "无菌注射用水",
    "reconstitutionVolumeText": "3ml",
    "reconstitutedStabilityText": "",
    "solvent": "无菌注射用水",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用地西他滨",
    "englishName": "",
    "specText": "10mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "5 mg/ml",
    "reconstitutionSolvent": "无菌注射用水",
    "reconstitutionVolumeText": "2ml",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": " 2°C-8°C  4 小时",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用地西他滨",
    "englishName": "",
    "specText": "25mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "5 mg/ml",
    "reconstitutionSolvent": "无菌注射用水",
    "reconstitutionVolumeText": "5ml",
    "reconstitutedStabilityText": "",
    "solvent": " 0.9% 的氯化钠注射液或 5% 葡萄糖注射50ml以上",
    "dilutedStabilityText": " 2°C-8°C  4 小时",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用地西他滨",
    "englishName": "",
    "specText": "50mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "5 mg/ml",
    "reconstitutionSolvent": "无菌注射用水",
    "reconstitutionVolumeText": "10ml",
    "reconstitutedStabilityText": "",
    "solvent": " 0.9% 的氯化钠注射液或 5% 葡萄糖注射50ml以上",
    "dilutedStabilityText": "2°C-8°C不超过 4 小时",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用培美曲塞二钠",
    "englishName": "",
    "specText": "100mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "25 mg/ml",
    "reconstitutionSolvent": "0.9%氯化钠溶液",
    "reconstitutionVolumeText": "4ml",
    "reconstitutedStabilityText": "",
    "solvent": "0.9%氯化钠注射液 100 mL",
    "dilutedStabilityText": "2°C-8°C 不超过 24 小时",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用培美曲塞二钠",
    "englishName": "",
    "specText": "200mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "25 mg/ml",
    "reconstitutionSolvent": "0.9%氯化钠溶液",
    "reconstitutionVolumeText": "8ml",
    "reconstitutedStabilityText": "",
    "solvent": "0.9%氯化钠注射液 100 mL",
    "dilutedStabilityText": "2°C-8°C 不超过 24 小时",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用培美曲塞二钠",
    "englishName": "",
    "specText": "500mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "25 mg/ml",
    "reconstitutionSolvent": "0.9%氯化钠溶液",
    "reconstitutionVolumeText": "20ml",
    "reconstitutedStabilityText": "",
    "solvent": "0.9%氯化钠注射液  100 mL",
    "dilutedStabilityText": "2°C-8°C 不超过 24 小时",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用奈达铂",
    "englishName": "",
    "specText": "10mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "2mg/ml",
    "reconstitutionSolvent": "0.9%氯化钠溶液",
    "reconstitutionVolumeText": "5ml",
    "reconstitutedStabilityText": "",
    "solvent": "0.9%氯化钠溶液 500ml",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用奈达铂",
    "englishName": "",
    "specText": "50mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "5mg/ml",
    "reconstitutionSolvent": "0.9%氯化钠溶液或5%木糖醇注射液",
    "reconstitutionVolumeText": "10ml",
    "reconstitutedStabilityText": "",
    "solvent": "0.9%氯化钠溶液 500ml",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用奥加伊妥珠单抗",
    "englishName": "Inotuzumab Ozogamicin for Injection",
    "specText": "1mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "0.25 mg/ml",
    "reconstitutionSolvent": "无菌注射用水",
    "reconstitutionVolumeText": "4ml",
    "reconstitutedStabilityText": "复溶到稀释之间的时间应 ≤ 4 小时。",
    "solvent": " 0.9% 氯化钠注射液  50 mL ",
    "dilutedStabilityText": "避光，勿冷冻，复溶到给药结束之间的最长时间应 ≤ 8 小时",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用奥沙利铂  ",
    "englishName": "",
    "specText": "50mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "5 mg/ml",
    "reconstitutionSolvent": "无菌注射用水或5%葡萄糖溶液",
    "reconstitutionVolumeText": "10ml",
    "reconstitutedStabilityText": "",
    "solvent": "5%葡萄糖注射液 250–500 mL",
    "dilutedStabilityText": " 2-8 ℃  24 小时",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用德曲妥珠单抗",
    "englishName": "",
    "specText": "100mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "20 mg/ml",
    "reconstitutionSolvent": "5%葡萄糖溶液",
    "reconstitutionVolumeText": "5ml",
    "reconstitutedStabilityText": "",
    "solvent": "100 ml 5% 葡萄糖溶液，不得使用氯化钠溶液。",
    "dilutedStabilityText": " 2-8 ℃  避光保存  24 小时。切勿冷冻。",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用恩美曲妥珠单抗",
    "englishName": "",
    "specText": "100mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "20 mg/ml",
    "reconstitutionSolvent": "无菌注射用水",
    "reconstitutionVolumeText": "5ml",
    "reconstitutedStabilityText": "",
    "solvent": " 250 ml 0.45% 氯化钠或 0.9% 氯化钠注射液。不应使用5%葡萄糖溶液。",
    "dilutedStabilityText": " 2-8 ℃ 避光不超过 24 小时，切勿冷冻或甩动输注袋。",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用恩美曲妥珠单抗",
    "englishName": "",
    "specText": "160mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "20 mg/ml",
    "reconstitutionSolvent": "无菌注射用水",
    "reconstitutionVolumeText": "8ml",
    "reconstitutedStabilityText": "",
    "solvent": "250 ml 0.45% 氯化钠或 0.9% 氯化钠注射液。不应使用5%葡萄糖溶液。",
    "dilutedStabilityText": " 2-8 ℃ 避光不超过 24 小时，切勿冷冻或甩动输注袋。",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用曲妥珠单抗",
    "englishName": "",
    "specText": "150mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "21 mg/ml",
    "reconstitutionSolvent": "无菌注射用水",
    "reconstitutionVolumeText": "7.2ml",
    "reconstitutedStabilityText": "",
    "solvent": "250 ml  0.9% 氯化钠注射液，不可使用 5% 的葡萄糖液",
    "dilutedStabilityText": " 2-8 ℃ 保存 48 小时，不得冷冻。 ",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用曲妥珠单抗",
    "englishName": "",
    "specText": "440mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "21 mg/ml",
    "reconstitutionSolvent": "无菌注射用水",
    "reconstitutionVolumeText": "20ml",
    "reconstitutedStabilityText": "复溶药液不超过 28 天；",
    "solvent": "250 ml  0.9% 氯化钠注射液，不可使用 5% 的葡萄糖液",
    "dilutedStabilityText": "2～8℃冷藏保存24 小时",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用曲妥珠单抗",
    "englishName": "",
    "specText": "60mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "21 mg/ml",
    "reconstitutionSolvent": "无菌注射用水",
    "reconstitutionVolumeText": "3ml",
    "reconstitutedStabilityText": "",
    "solvent": "250 ml  0.9% 氯化钠注射液，不可使用 5% 的葡萄糖液",
    "dilutedStabilityText": " 2-8 ℃ 保存 48 小时，不得冷冻。 ",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用氟达拉滨",
    "englishName": "",
    "specText": "50mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "25 mg/ml",
    "reconstitutionSolvent": "无菌注射用水",
    "reconstitutionVolumeText": "2ml",
    "reconstitutedStabilityText": "",
    "solvent": " 100 ml 0.9% 生理盐水",
    "dilutedStabilityText": "2-8°C 不超过 24 小时，室温不超过 8 小时",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用洛铂",
    "englishName": "",
    "specText": "50mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "10 mg/ml",
    "reconstitutionSolvent": "无菌注射用水",
    "reconstitutionVolumeText": "5ml",
    "reconstitutedStabilityText": " 2-8 ℃  4 小时",
    "solvent": "无要求",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用异环磷酰胺",
    "englishName": "Ifosfamide for Injection",
    "specText": "1000mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "50 mg/ml",
    "reconstitutionSolvent": "无菌注射用水",
    "reconstitutionVolumeText": "20ml",
    "reconstitutedStabilityText": "立即使用",
    "solvent": "5％葡萄糖注射液；0.9％氯化钠注射液；乳酸林格氏注射液；无菌注射用水",
    "dilutedStabilityText": "立即使用",
    "shareable": "不可共享",
    "rules": "水溶液不稳定，需现配现用"
  },
  {
    "drugName": "注射用环磷酰胺 ",
    "englishName": "",
    "specText": "200mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "20 mg/ml",
    "reconstitutionSolvent": "0.9%氯化钠溶液",
    "reconstitutionVolumeText": "10ml",
    "reconstitutedStabilityText": "",
    "solvent": "林格氏溶液，生理盐水或葡萄糖溶液 500ml以内",
    "dilutedStabilityText": "8°C以下 24h",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用环磷酰胺 ",
    "englishName": "",
    "specText": "1g",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "20 mg/ml",
    "reconstitutionSolvent": "0.9%氯化钠溶液",
    "reconstitutionVolumeText": "50ml",
    "reconstitutedStabilityText": "",
    "solvent": "入林格氏溶液，生理盐水或葡萄糖溶液 500ml內",
    "dilutedStabilityText": "8°C以下 24h",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用盐酸柔红霉素",
    "englishName": "",
    "specText": "20mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "2 mg/ml",
    "reconstitutionSolvent": "0.9%氯化钠溶液",
    "reconstitutionVolumeText": "10ml",
    "reconstitutedStabilityText": "",
    "solvent": " 0.9% 氯化钠注射液 250 ml ",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用硼替佐米",
    "englishName": "",
    "specText": "1mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "1 mg/ml",
    "reconstitutionSolvent": "0.9%氯化钠溶液",
    "reconstitutionVolumeText": "1ml",
    "reconstitutedStabilityText": "",
    "solvent": "无",
    "dilutedStabilityText": "25 ℃  8 小时",
    "shareable": "可共享",
    "rules": "不含抗菌性防腐剂"
  },
  {
    "drugName": "注射用硼替佐米",
    "englishName": "",
    "specText": "3.5mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "1 mg/ml",
    "reconstitutionSolvent": "0.9%氯化钠溶液",
    "reconstitutionVolumeText": "3.5ml",
    "reconstitutedStabilityText": "",
    "solvent": "无",
    "dilutedStabilityText": "25 ℃  8 小时",
    "shareable": "可共享",
    "rules": "不含抗菌性防腐剂"
  },
  {
    "drugName": "注射用紫杉醇（白蛋白结合型）",
    "englishName": "",
    "specText": "100mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "5 mg/ml",
    "reconstitutionSolvent": "0.9%氯化钠溶液",
    "reconstitutionVolumeText": "20ml",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "室温（20 ℃ -25 ℃ ）和室内光照保存 8 小时",
    "shareable": "可共享",
    "rules": "避免光照并放在 2 ℃ - 8 ℃ 冰箱内，最长可保存 8 小时"
  },
  {
    "drugName": "注射用维布妥昔单抗",
    "englishName": "Brentuximab Vedotin",
    "specText": "50mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "5 mg/ml",
    "reconstitutionSolvent": "无菌注射用水",
    "reconstitutionVolumeText": "10.5ml",
    "reconstitutedStabilityText": " 2-8 ℃ 不超过 24 小时",
    "solvent": "0.9%注射用氯化钠溶液 ，5% 注射用葡萄糖溶液，注射用乳酸林格液  150 mL",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用维泊妥珠单抗",
    "englishName": "Polatuzumab Vedotin",
    "specText": "30mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "20 mg/ml",
    "reconstitutionSolvent": "无菌注射用水",
    "reconstitutionVolumeText": "1.8ml",
    "reconstitutedStabilityText": " 2 ℃ -8 ℃ 下冷藏保存最长达 48 小时，或在 9 ℃ -25 ℃ 下保存最长 8 小时",
    "solvent": " 0.9% 氯化钠、或 0.45% 氯化钠或 5% 葡萄糖注射液  50 mL以上",
    "dilutedStabilityText": "如用0.9%氯化钠注射液稀释，在2°C-8°C条件下最多贮藏36小时，或在室温条件下（9°C-25°C）最多贮藏4小时；如用0.45%氯化钠注射液稀释，在2°C-8°C条件下最多贮藏18小时，在室温条件下（9°C-25°C）最多贮藏4小时；如用5%葡萄糖注射液稀释，在2°C-8°C条件下最多贮藏36小时，在室温条件下（9°C-25°C）最多贮藏6小时。\n",
    "shareable": "可共享",
    "rules": "使用不同的稀释液溶媒，其稀释液保存时间不同。"
  },
  {
    "drugName": "注射用维迪西妥单抗",
    "englishName": "Disitamab Vedotin For Injection",
    "specText": "20mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "10 mg/ml",
    "reconstitutionSolvent": "无菌注射用水",
    "reconstitutionVolumeText": "2ml",
    "reconstitutedStabilityText": "",
    "solvent": "250 mL 含有 0.9% 氯化钠或 5% 葡萄糖的输液袋中",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用维迪西妥单抗",
    "englishName": "Disitamab Vedotin For Injection",
    "specText": "60mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "10 mg/ml",
    "reconstitutionSolvent": "无菌注射用水",
    "reconstitutionVolumeText": "6ml",
    "reconstitutedStabilityText": " 2 ℃ -8 ℃ 保存24 小时",
    "solvent": " 250 mL 含有 0.9% 氯化钠或 5% 葡萄糖的输液袋中",
    "dilutedStabilityText": "室温下6小时；或 2 ℃ -8 ℃ 保存24 小时",
    "shareable": "可共享",
    "rules": "2025年4月最新版说明书"
  },
  {
    "drugName": "注射用盐酸苯达莫司汀",
    "englishName": "",
    "specText": "100mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "5 mg/ml",
    "reconstitutionSolvent": "无菌注射用水",
    "reconstitutionVolumeText": "20ml",
    "reconstitutedStabilityText": "",
    "solvent": " 500 mL 0.9% 氯化钠注射液， 2.5% 葡萄糖/0.45% 氯化钠注射液 。最终浓度范围应为：0.2-0.6 mg/mL。",
    "dilutedStabilityText": "2-8°C保存 24 小时，室温（15-30°C）以及室内光线照射条件保存 3 小时。",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用盐酸苯达莫司汀",
    "englishName": "",
    "specText": "25mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "5 mg/ml",
    "reconstitutionSolvent": "无菌注射用水",
    "reconstitutionVolumeText": "5ml",
    "reconstitutedStabilityText": "",
    "solvent": " 500 mL 0.9% 氯化钠注射液， 2.5% 葡萄糖/0.45% 氯化钠注射液 。最终浓度范围应为：0.2-0.6 mg/mL。",
    "dilutedStabilityText": "2-8°C保存 24 小时，室温（15-30°C）以及室内光线照射条件保存 3 小时。",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用盐酸表柔比星",
    "englishName": "",
    "specText": "10mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "2 mg/ml",
    "reconstitutionSolvent": "无菌注射用水或0.9%氯化钠溶液",
    "reconstitutionVolumeText": "5ml",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "",
    "shareable": "不共享",
    "rules": "用于静脉注射和膀胱灌注；不能冷藏储存，会形成凝胶。受控室温 （15–25°C） 下经过2至最多4小时平衡后，该凝胶产品将恢复为略微粘稠的流动溶液。"
  },
  {
    "drugName": "注射用贝林妥欧单抗",
    "englishName": "",
    "specText": "35ug",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "12.5 μg/ml",
    "reconstitutionSolvent": "无菌注射用水",
    "reconstitutionVolumeText": "3ml",
    "reconstitutedStabilityText": "",
    "solvent": " 0.9% 氯化钠注射液",
    "dilutedStabilityText": "2-8 ℃ 储存",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用达卡巴嗪",
    "englishName": "",
    "specText": "100mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": " 10 mg/ml",
    "reconstitutionSolvent": "0.9%氯化钠注射液",
    "reconstitutionVolumeText": "10ml",
    "reconstitutedStabilityText": "",
    "solvent": " 5% 葡萄糖溶液 250-500 mL ",
    "dilutedStabilityText": "",
    "shareable": "不可共享",
    "rules": "因本品对光和热极不稳定、遇光或热易变红，在水中不稳定，放置后溶液变浅红色。需临时配制，溶解后立即注射，并尽量避光。"
  },
  {
    "drugName": "注射用硫酸长春地辛 ",
    "englishName": "",
    "specText": "1mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "1 mg/ml",
    "reconstitutionSolvent": "无菌注射用水或0.9%氯化钠溶液",
    "reconstitutionVolumeText": "1ml",
    "reconstitutedStabilityText": "",
    "solvent": "0.9%氯化钠注射液， 5% 葡萄糖注射液 500 mL-1000 mL ",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用硫酸长春新碱",
    "englishName": "",
    "specText": "1mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "0.5 mg/ml",
    "reconstitutionSolvent": "0.9%氯化钠溶液",
    "reconstitutionVolumeText": "2ml",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "稀释液最多能储存12小时",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用阿扎胞苷",
    "englishName": "",
    "specText": "100mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "10 mg/ml",
    "reconstitutionSolvent": "无菌注射用水",
    "reconstitutionVolumeText": "10ml",
    "reconstitutedStabilityText": " 25 ℃  1 小时或 2 ℃ -8 ℃  8 小时",
    "solvent": "0.9%氯化钠注射液",
    "dilutedStabilityText": "",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用阿糖胞苷 ",
    "englishName": "",
    "specText": "100mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "100 mg/ml",
    "reconstitutionSolvent": "注射用水、0.9% 氯化钠或 5% 葡萄糖溶液，含或不含防腐剂",
    "reconstitutionVolumeText": "970μl",
    "reconstitutedStabilityText": "",
    "solvent": "5%葡萄糖注射液或0.9%氯化钠注射液",
    "dilutedStabilityText": "15-30℃保存48h",
    "shareable": "可共享",
    "rules": "需要用注射用抑菌水稀释或与苯甲醇的溶液"
  },
  {
    "drugName": "注射用阿糖胞苷 ",
    "englishName": "",
    "specText": "500mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "100 mg/ml",
    "reconstitutionSolvent": "注射用水、0.9% 氯化钠或 5% 葡萄糖溶液，含或不含防腐剂",
    "reconstitutionVolumeText": "4.7ml",
    "reconstitutedStabilityText": "",
    "solvent": "5%葡萄糖注射液或0.9%氯化钠注射液",
    "dilutedStabilityText": "15-30℃保存48h",
    "shareable": "可共享",
    "rules": "需要用注射用抑菌水稀释或与苯甲醇的溶液"
  },
  {
    "drugName": "注射用雷替曲塞",
    "englishName": "",
    "specText": "2mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "0.5 mg/ml",
    "reconstitutionSolvent": "无菌注射用水",
    "reconstitutionVolumeText": "4ml",
    "reconstitutedStabilityText": "",
    "solvent": "0.9% 的氯化钠注射液或 5% 的葡萄糖注射液 50-250 mL ",
    "dilutedStabilityText": " 2-8 ℃  24 小时，不需要避光",
    "shareable": "可共享",
    "rules": ""
  },
  {
    "drugName": "注射用顺铂",
    "englishName": "",
    "specText": "20mg",
    "drugVolumeText": "",
    "requiresReconstitution": "是",
    "concentration": "4 mg/ml",
    "reconstitutionSolvent": " 0.9% 氯化钠注射液或 5% 葡萄糖注射液",
    "reconstitutionVolumeText": "5ml",
    "reconstitutedStabilityText": "",
    "solvent": "",
    "dilutedStabilityText": "室温避光 24小时",
    "shareable": "可共享",
    "rules": ""
  }
];
