const DP_DRUG_FIELDS=["drugName","specText","drugVolumeText","requiresReconstitution","concentration","reconstitutionSolvent","reconstitutionVolumeText","reconstitutedStabilityText","solvent","dilutedStabilityText","shareable","riskLevel","rules"];
window.DRUG_KNOWLEDGE_SEED=[
["Ipilimumab Injection","50mg","10ml","No","","","","","","","Shareable","Low"],
["Irinotecan Hydrochloride Injection","100mg","5ml","No","","","","","","","Shareable","Low"],
["Irinotecan Hydrochloride Injection","40mg","2ml","No","","","","","","","Shareable","Low"],
["Irinotecan Hydrochloride Liposome Injection","43mg","10ml","No","","","","","","","Shareable","Low"],
["Utidelone Injection","50mg","5ml","No","","","","","","","Shareable","Low"],
["Etoposide Injection","100mg","5ml","No","","","","","","","Shareable","Low"],
["Sintilimab Injection","100mg","10ml","No","","","","","","","Shareable","Low"],
["Rituximab Injection","100mg","10ml","No","","","","","","","Shareable","Low"],
["Rituximab Injection","500mg","50ml","No","","","","","","","Shareable","Low"],
["Cadonilimab Injection","125mg","10ml","No","","","","","","","Shareable","Low"],
["Carboplatin Injection","100mg","10ml","No","","","","","","","Shareable","Low"],
["Carboplatin Injection","150mg","15ml","No","","","","","","","Shareable","Low"],
["Pegaspargase Injection","3750mg","5ml","No","","","","","","","Shareable","Low"],
["Thiotepa Injection","10mg","1ml","No","","","","","","","Shareable","Low"],
["Doxorubicin Hydrochloride for Injection","10mg","10ml","No","","","","","","","Shareable","Low"],
["Doxorubicin Liposome Injection","10mg","10ml","No","","","","","","","Shareable","Low"],
["Doxorubicin Liposome Injection","20mg","10ml","No","","","","","","","Shareable","Low"],
["Docetaxel Injection","20mg","1ml","No","","","","","","","Shareable","Low"],
["Docetaxel Injection","20mg","0.5ml","No","","","","","","","Shareable","Low"],
["Pembrolizumab Injection","100mg","4ml","No","","","","","","","Shareable","Low"],
["Serplulimab Injection","100mg","10ml","No","","","","","","","Shareable","Low"],
["Teniposide Injection","50mg","5ml","No","","","","","","","Shareable","Low"],
["Fluorouracil Injection","250mg","10ml","No","","","","","","","Shareable","Low"],
["Fluorouracil Injection","500mg","10ml","No","","","","","","","Shareable","Low"],
["Zuberitamab Injection","100mg","10ml","No","","","","","","","Shareable","Low"],
["Toripalimab Injection","80mg","2ml","No","","","","","","","Shareable","Low"],
["Methotrexate Injection","1000mg","10ml","No","","","","","","","Shareable","Low"],
["Methotrexate Injection","50mg","2ml","No","","","","","","","Shareable","Low"],
["Mitoxantrone Hydrochloride Liposome Injection","10mg","10ml","No","","","","","","","Shareable","Low"],
["Paclitaxel Injection","30mg","5ml","No","","","","","5% Glucose Injection","","Shareable","Low"],
["Nivolumab Injection","100mg","10ml","No","","","","","","","Shareable","Low"],
["Nivolumab Injection","40mg","4ml","No","","","","","","","Shareable","Low"],
["Eribulin Injection","1mg","2ml","No","","","","","","","Shareable","Low"],
["Cetuximab Injection","100mg","20ml","No","","","","","","","Shareable","Low"],
["Bevacizumab Injection","100mg","4ml","No","","","","","","","Shareable","Low"],
["Bevacizumab Injection","400mg","16ml","No","","","","","","","Shareable","Low"],
["Daratumumab Injection","400mg","20ml","No","","","","","","","Shareable","Low"],
["Ramucirumab Injection","500mg","50ml","No","","","","","","","Shareable","Low"],
["Cisplatin Injection","30mg","6ml","No","","","","","","","Shareable","Low"],
["Cisplatin Injection","50mg","50ml","No","","","","","","","Shareable","Low"],
["Homoharringtonine Injection","1mg","1ml","No","","","","","","","Shareable","Low"],
["Oxaliplatin and Mannitol Injection","50mg","100ml","No","","","","","","","Shareable","Low"],
["Busulfan Injection","60mg","10ml","No","","","","","","","Shareable","Low"],
["Vinorelbine Tartrate Injection","10mg","1ml","No","","","","","","","Shareable","Low"],
["Paclitaxel Liposome for Injection","30mg","","Yes","3 mg/ml","5% Glucose Injection","10ml","","250-500 mL 5% Glucose Injection","Room temperature (25 °C) under indoor light for 24 hours","Shareable","Medium","This product must be reconstituted and diluted only with 5% Glucose Injection. Do not use normal saline or other solutions for reconstitution or dilution to avoid liposome aggregation."],
["Arsenic Trioxide for Injection","5mg","","Yes","2.5mg/ml","0.9% Sodium Chloride Injection","2ml","","5% Glucose Injection USPor 0.9% Sodium Chloride Injection 500 mL","Store at 20-25 °C; excursions permitted at 15-30 °C; do not freeze","Shareable","Medium"],
["Mitomycin for Injection","10mg","","Yes","0.5mg/ml","Sterile Water for Injection","20ml","","","Avoid temperatures above 40 °C","Shareable","Medium"],
["Leuprorelin Acetate Microspheres for Injection","11.25mg","","Yes","11.25 mg/ml","dedicated injection solvent supplied with the product","1ml","","","Protect from light below 25 °C","Not shareable; subcutaneous injection; usually full-unit use","High"],
["Inetetamab for Injection","50mg","","Yes","20 mg/ml","Sterile Water for Injection","2.5ml","Use immediately","250 mL 0.9% Sodium Chloride Injection, do not use5% Glucose Injection","Store dry and protected from light at 2-8 °C","Shareable","High","To prevent microbial contamination, use the dissolved drug solution immediately after reconstitution; vigorous shaking is strictly prohibited."],
["Idarubicin for Injection","10mg","","Yes","1 mg/ml","Water for Injection (USP)","10ml","","None","Protect from light at 15-30 °C","Not shareable; IV injection only","High"],
["Idarubicin Hydrochloride for Injection","5mg","","Yes","1 mg/ml","Sterile Water for Injection","5ml","","None","Store at controlled room temperature of 15-30 °C and protect from light.","Not shareable; IV injection only","High"],
["Bleomycin Hydrochloride for Injection","15mg","","Yes","3mg/ml","Sterile Water for Injection or 0.9% Sodium Chloride Injection","5ml","","0.9% Sodium Chloride Injection","Stable at room temperature for 24 hours","Shareable","Low"],
["Carboplatin for Injection","50mg","","Yes","10 mg/ml","5% Glucose Solution","5ml","","5% Glucose Solution or 0.9% Sodium Chloride Injection 100 mL or more","","Shareable","Low"],
["Carfilzomib for Injection","60mg","","Yes","2 mg/ml","Sterile Water for Injection","29ml","","50 mL or 100 mL 5% Glucose Injection","Stable at 2-8 °C for 24 hours; stable at 15-30 °C for 4 hours","Shareable","Medium"],
["Siltuximab for Injection","400mg","","Yes","20 mg/ml","Sterile Water for Injection","20ml","No more than 2 hours","250 mL 5% Glucose","Complete administration within 6 hours after preparation.","Shareable","Low","Contains no preservatives"],
["Gemcitabine Hydrochloride for Injection","1000mg","","Yes","38 mg/ml","0.9% Sodium Chloride Solution","25ml","","0.9% Sodium Chloride Injection","Stable at 20-25 °C for 24 h; do not refrigerate","Shareable","Medium"],
["Gemcitabine Hydrochloride for Injection","200mg","","Yes","38 mg/ml","0.9% Sodium Chloride Solution","5ml","","0.9% Sodium Chloride Injection","Stable at 20-25 °C for 24 h; do not refrigerate","Shareable","Medium"],
["Pirarubicin Hydrochloride for Injection","10mg","","Yes","1 mg/ml","5% Glucose Injection or Water for Injection","10ml","","","Room temperature for 6 hours","Shareable","Low"],
["Degarelix for Injection","120mg","","Yes","40 mg/ml","Sterile Water for Injection","3ml","","Sterile Water for Injection","","Shareable","Low"],
["Decitabine for Injection","10mg","","Yes","5 mg/ml","Sterile Water for Injection","2ml","","","2-8 °C for 4 hours","Shareable","Medium"],
["Decitabine for Injection","25mg","","Yes","5 mg/ml","Sterile Water for Injection","5ml","","0.9% Sodium Chloride Injection or 5% Glucose Injection, at least 50 mL","2-8 °C for 4 hours","Shareable","Medium"],
["Decitabine for Injection","50mg","","Yes","5 mg/ml","Sterile Water for Injection","10ml","","0.9% Sodium Chloride Injection or 5% Glucose Injection, at least 50 mL","2-8 °C for no more than 4 hours","Shareable","Medium"],
["Pemetrexed Disodium for Injection","100mg","","Yes","25 mg/ml","0.9% Sodium Chloride Solution","4ml","","0.9% Sodium Chloride Injection 100 mL","2-8 °C for no more than 24 hours","Shareable","Medium"],
["Pemetrexed Disodium for Injection","200mg","","Yes","25 mg/ml","0.9% Sodium Chloride Solution","8ml","","0.9% Sodium Chloride Injection 100 mL","2-8 °C for no more than 24 hours","Shareable","Medium"],
["Pemetrexed Disodium for Injection","500mg","","Yes","25 mg/ml","0.9% Sodium Chloride Solution","20ml","","0.9% Sodium Chloride Injection 100 mL","2-8 °C for no more than 24 hours","Shareable","Medium"],
["Nedaplatin for Injection","10mg","","Yes","2mg/ml","0.9% Sodium Chloride Solution","5ml","","0.9% Sodium Chloride Solution 500 mL","","Shareable","Low"],
["Nedaplatin for Injection","50mg","","Yes","5mg/ml","0.9% Sodium Chloride Solution or 5% Xylitol Injection","10ml","","0.9% Sodium Chloride Solution 500 mL","","Shareable","Low"],
["Inotuzumab Ozogamicin for Injection","1mg","","Yes","0.25 mg/ml","Sterile Water for Injection","4ml","The time from reconstitution to dilution should be ≤ 4 hours.","0.9% Sodium Chloride Injection 50 mL","Protect from light; do not freeze; the maximum time from reconstitution to completion of administration should be ≤ 8 hours","Shareable","Medium"],
["Oxaliplatin for Injection","50mg","","Yes","5 mg/ml","Sterile Water for Injection or 5% Glucose Solution","10ml","","5% Glucose Injection 250–500 mL","2-8 °C for 24 hours","Shareable","Medium"],
["Trastuzumab Deruxtecan for Injection","100mg","","Yes","20 mg/ml","5% Glucose Injection","5ml","","100 mL 5% Glucose Solution; do not use sodium chloride injection","Store protected from light at 2-8 °C for 24 hours. Do not freeze.","Shareable","Medium"],
["Trastuzumab Emtansine for Injection","100mg","","Yes","20 mg/ml","Sterile Water for Injection","5ml","","250 mL 0.45% Sodium Chlorideor 0.9% Sodium Chloride Injection.should not use5% Glucose Solution.","Protect from light at 2-8 °C for no more than 24 hours; do not freeze or shake the infusion bag.","Shareable","Medium"],
["Trastuzumab Emtansine for Injection","160mg","","Yes","20 mg/ml","Sterile Water for Injection","8ml","","250 mL 0.45% Sodium Chlorideor 0.9% Sodium Chloride Injection.should not use5% Glucose Solution.","Protect from light at 2-8 °C for no more than 24 hours; do not freeze or shake the infusion bag.","Shareable","Medium"],
["Trastuzumab for Injection","150mg","","Yes","21 mg/ml","Sterile Water for Injection","7.2ml","","250 mL 0.9% Sodium Chloride Injection; do not use 5% Glucose Solution.","Store at 2-8 °C for 48 hours; do not freeze.","Shareable","Medium"],
["Trastuzumab for Injection","440mg","","Yes","21 mg/ml","Sterile Water for Injection","20ml","Reconstituted solution: no more than 28 days.","250 mL 0.9% Sodium Chloride Injection; do not use 5% Glucose Solution.","Refrigerate at 2-8 °C for 24 hours","Shareable","Medium"],
["Trastuzumab for Injection","60mg","","Yes","21 mg/ml","Sterile Water for Injection","3ml","","250 mL 0.9% Sodium Chloride Injection; do not use 5% Glucose Solution.","Store at 2-8 °C for 48 hours; do not freeze.","Shareable","Medium"],
["Fludarabine for Injection","50mg","","Yes","25 mg/ml","Sterile Water for Injection","2ml","","100 mL 0.9% normal saline","2-8 °C for no more than 24 hours; room temperature for no more than 8 hours","Shareable","Medium"],
["Lobaplatin for Injection","50mg","","Yes","10 mg/ml","Sterile Water for Injection","5ml","2-8 °C for 4 hours","No specific requirement","","Shareable","Medium"],
["Ifosfamide for Injection","1000mg","","Yes","50 mg/ml","Sterile Water for Injection","20ml","Use immediately","5% Glucose Injection; 0.9% Sodium Chloride Injection; Lactated Ringer's Injection; Sterile Water for Injection","Use immediately","Not shareable","High","The aqueous solution is unstable and should be prepared immediately before use."],
["Cyclophosphamide for Injection","200mg","","Yes","20 mg/ml","0.9% Sodium Chloride Injection","10ml","","Ringer's solution, normal saline, or glucose solution, no more than 500 mL","Below 8 °C for 24 h","Shareable","Low"],
["Cyclophosphamide for Injection","1g","","Yes","20 mg/ml","0.9% Sodium Chloride Injection","50ml","","Add to Ringer's solution, normal saline, or glucose solution, no more than 500 mL","Below 8 °C for 24 h","Shareable","Low"],
["Daunorubicin Hydrochloride for Injection","20mg","","Yes","2 mg/ml","0.9% Sodium Chloride Injection","10ml","","0.9% Sodium Chloride Injection 250 mL","","Shareable","Low"],
["Bortezomib for Injection","1mg","","Yes","1 mg/ml","0.9% Sodium Chloride Injection","1ml","","None","25 °C for 8 hours","Shareable","Low","Does not contain antimicrobial preservatives"],
["Bortezomib for Injection","3.5mg","","Yes","1 mg/ml","0.9% Sodium Chloride Injection","3.5ml","","None","25 °C for 8 hours","Shareable","Low","Does not contain antimicrobial preservatives"],
["Paclitaxel for Injection (Albumin-bound)","100mg","","Yes","5 mg/ml","0.9% Sodium Chloride Injection","20ml","","","Store at room temperature (20-25 °C) under indoor light for 8 hours","Shareable","Medium","Protect from light and store in a refrigerator at 2-8 °C for up to 8 hours."],
["Brentuximab Vedotin for Injection","50mg","","Yes","5 mg/ml","Sterile Water for Injection","10.5ml","2-8 °C for no more than 24 hours","0.9% Sodium Chloride Injection, 5% Glucose Injection, or Lactated Ringer's Injection, 150 mL","","Shareable","Medium"],
["Polatuzumab Vedotin for Injection","30mg","","Yes","20 mg/ml","Sterile Water for Injection","1.8ml","Store refrigerated at 2-8 °C for up to 48 hours, or at 9-25 °C for up to 8 hours","0.9% Sodium Chloride Injection, 0.45% Sodium Chloride Injection, or 5% Glucose Injection, at least 50 mL","If diluted with 0.9% Sodium Chloride Injection, store for up to 36 hours at 2-8 °C or up to 4 hours at room temperature (9-25 °C). If diluted with 0.45% Sodium Chloride Injection, store for up to 18 hours at 2-8 °C or up to 4 hours at room temperature (9-25 °C). If diluted with 5% Glucose Injection, store for up to 36 hours at 2-8 °C or up to 6 hours at room temperature (9-25 °C).","Shareable","Medium","The storage time of the diluted solution differs by diluent."],
["Disitamab Vedotin for Injection","20mg","","Yes","10 mg/ml","Sterile Water for Injection","2ml","","250 mL infusion bag containing 0.9% Sodium Chloride Injection or 5% Glucose Injection","","Shareable","Low"],
["Disitamab Vedotin for Injection","60mg","","Yes","10 mg/ml","Sterile Water for Injection","6ml","Store at 2-8 °C for 24 hours","250 mL infusion bag containing 0.9% Sodium Chloride or 5% Glucose","Room temperature for 6 hours; or store at 2-8 °C for 24 hours","Shareable","Medium","Latest package insert, April 2025"],
["Bendamustine Hydrochloride for Injection","100mg","","Yes","5 mg/ml","Sterile Water for Injection","20ml","","500 mL 0.9% Sodium Chloride Injection or 2.5% Glucose/0.45% Sodium Chloride Injection. Final concentration range should be 0.2-0.6 mg/mL.","Store at 2-8 °C for 24 hours; at room temperature (15-30 °C) under indoor light for 3 hours.","Shareable","Medium"],
["Bendamustine Hydrochloride for Injection","25mg","","Yes","5 mg/ml","Sterile Water for Injection","5ml","","500 mL 0.9% Sodium Chloride Injection or 2.5% Glucose/0.45% Sodium Chloride Injection. Final concentration range should be 0.2-0.6 mg/mL.","Store at 2-8 °C for 24 hours; at room temperature (15-30 °C) under indoor light for 3 hours.","Shareable","Medium"],
["Epirubicin Hydrochloride for Injection","10mg","","Yes","2 mg/ml","Sterile Water for Injection or 0.9% Sodium Chloride Solution","5ml","","","","Not shareable","High","For intravenous injection and bladder instillation; do not refrigerate because gel formation may occur. After equilibration at controlled room temperature (15-25 °C) for 2 to up to 4 hours, the gelled product returns to a slightly viscous flowing solution."],
["Blinatumomab for Injection","35ug","","Yes","12.5 μg/ml","Sterile Water for Injection","3ml","","0.9% Sodium Chloride Injection","Store at 2-8 °C","Shareable","Medium"],
["Dacarbazine for Injection","100mg","","Yes","10 mg/ml","0.9% Sodium Chloride Injection","10ml","Use immediately","5% Glucose Solution 250-500 mL","Use immediately","Not shareable","High","This product is highly unstable to light and heat and readily turns red when exposed to light or heat. It is unstable in water, and the solution becomes pale red after standing. Prepare immediately before use, inject immediately after dissolution, and protect from light as much as possible."],
["Vindesine Sulfate for Injection","1mg","","Yes","1 mg/ml","Sterile Water for Injection or 0.9% Sodium Chloride  Injection","1ml","","0.9% Sodium Chloride Injection or 5% Glucose Injection, 500-1000 mL","","Shareable","Low"],
["Vincristine Sulfate for Injection","1mg","","Yes","0.5 mg/ml","0.9% Sodium Chloride Solution","2ml","","","Diluted solution can be stored for up to 12 hours","Shareable","Low"],
["Azacitidine for Injection","100mg","","Yes","10 mg/ml","Sterile Water for Injection","10ml","25 °C for 1 hour or 2-8 °C for 8 hours","0.9% Sodium Chloride Injection","","Shareable","Medium"],
["Cytarabine for Injection","100mg","","Yes","100 mg/ml","Water for Injection, 0.9% Sodium Chloride, or 5% Glucose Injection, with or without preservatives","970 μL","","5% Glucose Injection or 0.9% Sodium Chloride Injection","Store at 15-30 °C for 48 h","Shareable","Low","Requires dilution with bacteriostatic water for injection or a benzyl alcohol-containing solution"],
["Cytarabine for Injection","500mg","","Yes","100 mg/ml","Water for Injection, 0.9% Sodium Chloride, or 5% Glucose Solution, with or without preservatives","4.7ml","","5% Glucose Injection or 0.9% Sodium Chloride Injection","Store at 15-30 °C for 48 h","Shareable","Low","Requires dilution with bacteriostatic water for injection or a benzyl alcohol-containing solution"],
["Raltitrexed for Injection","2mg","","Yes","0.5 mg/ml","Sterile Water for Injection","4ml","","0.9% Sodium Chloride Injection or 5% Glucose Injection 50-250 mL","2-8 °C for 24 hours; protection from light is not required","Shareable","Medium"],
["Cisplatin for Injection","20mg","","Yes","4 mg/ml","0.9% Sodium Chloride Injection or 5% Glucose Injection","5ml","","","Room temperature, protected from light, for 24 hours","Shareable","Low"]
].map(row=>Object.fromEntries(DP_DRUG_FIELDS.map((field,index)=>[field,row[index]||""])));
